
const parts = [
    'SewageWellCover',
    'RainwaterWellCover',
    'SailUpstreamWellCover',
    'MunicipalWaterIntakePlug',
    'LiquefiedPetroleumGasBottleChangingStationAndAncillaryFacilities',
    'GasWellCover',
    'HighVoltageWireTower',
    'RingNetworkCabinet',
    'ElectricPowerWellCover',
    'StreetLamp',
    'LandscapeLamp',
    'StreetLampWellCover',
    'MunicipalPublicBox',
    'RodBody',
    'MonitoringFacility',
    'SmallMicroBaseStation',
    'CableTrench',
    'WeakCurrentIntegratedBox',
    'FireHydrant',
    'FireCover',
    'ThermalPowerWellCover',
    'TelevisionWellCover',
    'CommunicationManholeCover',
    'MacroBaseStation',
    'TelephoneBooth',
    'PublicSecurityTrafficPoliceManholeCover',
    'Booth',
    'InformationKiosk',
    'Mailbox',
    'NewsStand',
    'VendingMachine',
    'SpecialWellCover',
    'MotorVehicleLane',
    'NonMotorVehicleLane',
    'Sidewalk',
    'BlindRoad',
    'RoadFlatSideStone',
    'ParkingLot',
    'BusStopKiosk',
    'TrafficPostbox',
    'TaxiStationBoard',
    'TrafficSigns',
    'TrafficLight',
    'TrafficSignalFacilities',
    'RoadInformationDisplayScreen',
    'RoadSoundproofBarrier',
    'TrafficGuardrail',
    'CrashColumn',
    'DecelerationZone',
    'StreetNameplate',
    'OtherSignage',
    'LevelCrossingBridge',
    'OverheadViaduct',
    'Footbridge',
    'UndergroundPassage',
    'Culvert',
    'Tunnel',
    'PublicToilet',
    'GarbageTransferStation',
    'GarbageSortingPoint',
    'Dustbin',
    'GarbageDisposalSite',
    'LightBoxAndNeonLamp',
    'AdvertisingPlaque',
    'EnvironmentalProtectionMonitoringStation',
    'MunicipalLevelMeteorologicalMonitoringStation',
    'NoiseDisplayScreen',
    'NationalGroundwaterMonitoringWell',
    'Park',
    'Square',
    'Greenland',
    'OldAndFamousTree',
    'StreetTree',
    'GreenlandAncillaryFacilities',
    'GreenlandMaintenanceFacilities',
    'EmergencyShelter',
    'AirDefenceFortifications',
    'Gas',
    'LiquefiedGasStation',
    'ChargingPile',
    'WaterConservancyAffiliatedFacilities',
    'WatersGuardrail',
    'RiverBank'
]

const parts = [
    'CombustibleGasMonitor',
    'pressureGauge',
    'FlowMeter',
    'ResidualChlorineMonitor',
    'BODMonitor',
    'Voltage',
    'Current',
    'OperatingStatus'
]
const res = parts.reduce((pre, item) => {
    pre[item] = {
        "id": item,
        "code": item,
        "path": `/city_digital_assets/TOT_assets_mgr/${item}`,
        "componentProps": {
            "objectTypeId": item
          }
    }
    return pre
}, {})

console.log(`%%%%%%%%%%%%%%%%%%%%%%   ${JSON.stringify(res)}`, )


